name : AutoSave
main : hancho.plugin.nukkt.autosave.AutoSave
author : Hancho
version : 1.0.0
api : [1.0.0]

commands:
  autosave:
    description: 서버 자동저장 시스템 명령어
    permission : "op"
    aliases: [as]